# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trainer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trainer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrainer.proto\x12\x07trainer\"&\n\x0eRetrainRequest\x12\x14\n\x0cjson_payload\x18\x01 \x01(\t\"3\n\x0fRetrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2N\n\x0eTrainerService\x12<\n\x07Retrain\x12\x17.trainer.RetrainRequest\x1a\x18.trainer.RetrainResponseB\n\xaa\x02\x07Trainerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Trainer'
  _globals['_RETRAINREQUEST']._serialized_start=26
  _globals['_RETRAINREQUEST']._serialized_end=64
  _globals['_RETRAINRESPONSE']._serialized_start=66
  _globals['_RETRAINRESPONSE']._serialized_end=117
  _globals['_TRAINERSERVICE']._serialized_start=119
  _globals['_TRAINERSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
